### ISSUE TITLE
TODO List Before v1.0.0 Release

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode#3]
# Code Side:
- [x] Give user a **notice** once they change the front-end framework - a pop up message and a status bar message will show up

- [x] Fix the key binding on Mac **`ctrl + cmd + alt + n`** and **`ctrl + cmd + alt + p`** not working - replace with other keys (Mac only)

- [x] Add essential dependencies and remove the redundant dependencies from package.json - reduce the extension size

- [x] Add more commonly used snippets in terms of PHP @DaFa66 @jakecastelli 

- [x] Write essential comments in case collaboration or future maintains
 
- [x] Code Refactor

- [x] Figure out how to make it compatible even with lower version of VSCode as mentioned here #2 

- [x] A tinny new feature that can persist user's Nitro Framework selection

# File Structure Side:
- [x] Structure the front-end framework snippets into a separate folder - such as snippets/**front-end-framework**/milligram.json - in order to separate trongate php snippets and front-end frameworks

- [x] Remove the junk folder as it is not needed

# README Side:

- [x] Add explanation for Nitro usage

- [x] Demo for Nitro - suggestion: if you could figure out the way to show your key pressed on the screen that would be helpful @DaFa66 

- [x] Add to snippet table if any new snippet gets added

# Testing Side:

- [x] Fully test it on Windows @DaFa66 

- [x] Fully test it on MacOS @jakecastelli 

- [x] Fully test it on Linux @jakecastelli

**Comment by DaFa66** [comment]
Hey Jake,

Great work in getting the Nitro dropdown to switch between frameworks!

I've tested it on Windows, all works well.  I've removed the junk folder and created a new demo, but it's too big to upload.  So might clip it down or split it up into sections

Cheers,
Si

**Comment by jakecastelli** [comment]
Nice work mate! You are 10x ahead of me now!

Off topic: just watched your video on the forum, very clear and intuitive, I thought you were gonna speak in the video ;)

**Comment by jakecastelli** [comment]
The v1.0.0 has been released!
