### ISSUE TITLE
[TODO] Release v1.0.3

### ISSUE THREAD

**Issue by jakecastelli** [jakecastelli/trongate-vscode#30]
- [x] Edit README - mention the changes - #29

- [x] Add license - MIT - #29

- [x] Change the version number - #29
